[program:mikopbx-ami]
command=php /var/www/your-laravel-app/artisan mikopbx:listen
directory=/var/www/your-laravel-app
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
stopwaitsecs=30
stderr_logfile=/var/log/supervisor/mikopbx-ami.err.log
stdout_logfile=/var/log/supervisor/mikopbx-ami.out.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB
